#include "RealmTest.h"
#include "Barony.h"
#include "LandTerritory.h"
#include "LandArmy.h"
#include "NavalFleet.h"
#include "Realm.h"
#include "Player.h"
#include "Game.h"

void RealmTest::test()
{
}

void RealmTest::test1()
{
	std::string testName = "county providing bonus yields";

	Game game("");
	Player player1(game);
	Player player2(game);
	Player player3(game);
	LandTerritory territory1(0);
	LandTerritory territory2(1);
	LandTerritory territory3(2);
	LandTerritory territory4(3);

	const double landArmyYield = 0.4;
	const double navalFleetYield = 0.1;
	std::unique_ptr<Estate> barony1 = std::make_unique<Barony>(territory1, landArmyYield, navalFleetYield);
	std::unique_ptr<Estate> barony2 = std::make_unique<Barony>(territory2, landArmyYield, navalFleetYield);
	std::unique_ptr<Estate> barony3 = std::make_unique<Barony>(territory3, landArmyYield, navalFleetYield);
	std::unique_ptr<Estate> barony4 = std::make_unique<Barony>(territory4, landArmyYield, navalFleetYield);
	std::unique_ptr<Estate> county = std::make_unique<Estate>(Title::count);

	county.get()->addSubfief(barony1.get());
	county.get()->addSubfief(barony2.get());
	county.get()->addSubfief(barony3.get());
	county.get()->addSubfief(barony4.get());

	barony1.get()->setRuler(&player1);
	barony2.get()->setRuler(&player1);
	barony3.get()->setRuler(&player2);
	county.get()->setRuler(&player2);
	barony4.get()->setRuler(&player3);  // player3 will not be apart of player2's realm.

	player2.getRealm().getRelationshipManager().addVassal(player1);

	player2.getRealm().getEstateManager().handleFiefYields();
	player1.getRealm().getEstateManager().handleFiefYields();
	if(territory1.getArmy() != nullptr)
	{
		bool result = false;
		std::string message = "unexpected land army yielded";
		testReport(testName, result, message);
		return;
	}

	// Attempts to successfully yield a land army through yields only generated by bonus yields provided by county to baronies.
	// 150 loops executed as this should guaruntee surpassing yield threshold for any sanely chosen threshold value.
	for(int i = 0; i < 150; ++i)
	{
		player2.getRealm().getEstateManager().handleFiefYields();
	}
	player1.getRealm().getEstateManager().handleFiefYields();
	if(territory1.getArmy() == nullptr)
	{
		bool result = false;
		std::string message = "no land army yielded to territory";
		testReport(testName, result, message);
		return;
	}

	bool result = true;
	testReport(testName, result);
}
